FROM node:24-alpine AS builder
WORKDIR /app

ARG NUXT_BETTER_AUTH_SECRET
ARG NUXT_PUBLIC_SITE_URL
ARG NUXT_PUBLIC_VAPID_PUBLIC_KEY
ARG NUXT_PUBLIC_ENV 

ENV NUXT_BETTER_AUTH_SECRET=$NUXT_BETTER_AUTH_SECRET
ENV NUXT_PUBLIC_SITE_URL=$NUXT_PUBLIC_SITE_URL
ENV NUXT_PUBLIC_VAPID_PUBLIC_KEY=$NUXT_PUBLIC_VAPID_PUBLIC_KEY
ENV NUXT_PUBLIC_ENV=$ENV 

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:24-alpine
WORKDIR /app
COPY --from=builder /app/.output ./

EXPOSE 3000
CMD ["node", "server/index.mjs"]