FROM node:24-alpine AS builder
WORKDIR /app

ARG NUXT_BETTER_AUTH_SECRET
ARG NUXT_PUBLIC_SITE_URL
ARG NUXT_PUBLIC_VAPID_PUBLIC_KEY
ARG MONGO_URI
ARG MONGO_DB
ARG SYSTEM_MAINTENANCE_KEY
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG MS_CLIENT_ID
ARG MS_CLIENT_SECRET
ARG TMDB_API_KEY
ARG TMDB_BASE_URL
ARG OMDB_API_KEY
ARG OMDB_BASE_URL
ARG VAPID_PRIVATE_KEY
ARG VAPID_SUBJECT
ARG ENV

ENV NUXT_BETTER_AUTH_SECRET=$NUXT_BETTER_AUTH_SECRET
ENV NUXT_PUBLIC_SITE_URL=$NUXT_PUBLIC_SITE_URL
ENV NUXT_PUBLIC_VAPID_PUBLIC_KEY=$NUXT_PUBLIC_VAPID_PUBLIC_KEY
ENV MONGO_URI=$MONGO_URI
ENV MONGO_DB=$MONGO_DB
ENV SYSTEM_MAINTENANCE_KEY=$SYSTEM_MAINTENANCE_KEY
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV MS_CLIENT_ID=$MS_CLIENT_ID
ENV MS_CLIENT_SECRET=$MS_CLIENT_SECRET
ENV TMDB_API_KEY=$TMDB_API_KEY
ENV TMDB_BASE_URL=$TMDB_BASE_URL
ENV OMDB_API_KEY=$OMDB_API_KEY
ENV OMDB_BASE_URL=$OMDB_BASE_URL
ENV VAPID_PRIVATE_KEY=$VAPID_PRIVATE_KEY
ENV VAPID_SUBJECT=$VAPID_SUBJECT
ENV ENV=$ENV

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:24-alpine
WORKDIR /app
COPY --from=builder /app/.output ./

EXPOSE 3000
CMD ["node", "server/index.mjs"]